logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
server:
  port: 9090


spring:
  datasource:
    url: "jdbc:sqlserver://localhost;databaseName=everyloop"
    username: java
    password: ${DATABASE_PSW}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: combo-service
  cloud:
    consul:
      discovery:
        register: false
        registerHealthCheck: false
      config:
        enabled: false
      host: localhost
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: countries-service
          uri: lb://countries-service
          predicates:
            - Path=/countries/**
          filters:
            - RewritePath=/countries/(?<path>.*), /countries/$\{path}
        - id: songs-service
          uri: lb://songs
          predicates:
            - Path=/songs/**
          filters:
            - RewritePath=/songs/(?<path>.*), /songs/$\{path}
